version: '2'
services:
    mccrm-app:
        image: mccrm
        external_links:
            - mccrm-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mccrm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mccrm-postgresql:
        extends:
            file: postgresql.yml
            service: mccrm-postgresql
